language: python
sudo: false
python:
  - 2.7
  - 3.5
  - 3.6
env:
  - DJANGO_VERSION=1.8.*
  - DJANGO_VERSION=1.9.*
  - DJANGO_VERSION=1.10.*
  - DJANGO_VERSION=1.11.*
install:
  - pip install -U pip wheel
  - pip install -U setuptools
  - pip install django==$DJANGO_VERSION
  - pip install -U -r test-requires.txt
before_script: flake8 django_redshift_backend
script:
  - py.test
  - python setup.py sdist bdist_wheel
  - python setup.py check -s -r
